//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
 
package CustomerOrderAndFulfillment.CommonSchemaElements;
 
 
public	class	Address implements Cloneable
{
	public	String	name;
	public	int	zip;
	public	String	city;
	public	String	country;
			
	//default constructor
	public	Address()
	{
		name = "";
		zip = 0 ;
		city = "";
		country = "";
	}
			
	//Clonable Override
	@Override  public	Address clone()	throws CloneNotSupportedException
	{
		Address	 instance = new Address() ;
		instance.name = name ;
		instance.zip = zip ;
		instance.city = city ;
		instance.country = country ;
		return instance;
	}
			
	//DeepCopy
	public	void DeepCopy(Address rhs)
	{
		name = rhs.name ;
		zip = rhs.zip ;
		city = rhs.city ;
		country = rhs.country ;
	}
			
}


