//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
 
package CustomerOrderAndFulfillment.CommonSchemaElements;
 
 
public	class	OrderItem implements Cloneable
{
	public	String	title;
	public	String	note;
	public	int	quantity;
	public	double	price;
			
	//default constructor
	public	OrderItem()
	{
		title = "";
		note = "";
		quantity = 0 ;
		price = 0.0 ;
	}
			
	//Clonable Override
	@Override  public	OrderItem clone()	throws CloneNotSupportedException
	{
		OrderItem	 instance = new OrderItem() ;
		instance.title = title ;
		instance.note = note ;
		instance.quantity = quantity ;
		instance.price = price ;
		return instance;
	}
			
	//DeepCopy
	public	void DeepCopy(OrderItem rhs)
	{
		title = rhs.title ;
		note = rhs.note ;
		quantity = rhs.quantity ;
		price = rhs.price ;
	}
			
}


