//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
//Auto generated code
 
#pragma once
using System::String;
using System::ICloneable;
using System::Collections::Generic::List;
using System::SerializableAttribute;
 
 
 
 
 
 
namespace CustomerOrderAndFulfillment
{
	namespace CommonSchemaElements
	{
 
		[SerializableAttribute]
		public ref class	CreditCardDetails: public ICloneable
		{
		public:
			String^			CCNumber;
			String^			ExpirationDate;
			
			//default constructor
			CreditCardDetails()
			{
				CCNumber = String::Empty;
				ExpirationDate = String::Empty;
			}
			
			//copy constuctor
			CreditCardDetails( CreditCardDetails%  rhs){*this = rhs;}
			
			//IClonable Override
			virtual	Object^ Clone()
			{
				CreditCardDetails^	 instance = gcnew CreditCardDetails() ;
				*instance = *this ;
				return instance;
			}
			
			//= operator
			CreditCardDetails% operator = ( CreditCardDetails%  rhs)
			{
				CCNumber = rhs.CCNumber ;
				ExpirationDate = rhs.ExpirationDate ;
				return *this;
			}
			
			//DeepCopy
			void	DeepCopy ( CreditCardDetails^  from)
			{
				CCNumber = from->CCNumber ;
				ExpirationDate = from->ExpirationDate ;
			}
			
		};
 
		[SerializableAttribute]
		public ref class	OrderItem: public ICloneable
		{
		public:
			String^			title;
			String^			note;
			int			quantity;
			System::Decimal			price;
			
			//default constructor
			OrderItem()
			{
				title = String::Empty;
				note = String::Empty;
				quantity = 0 ;
				price = 0 ;
			}
			
			//copy constuctor
			OrderItem( OrderItem%  rhs){*this = rhs;}
			
			//IClonable Override
			virtual	Object^ Clone()
			{
				OrderItem^	 instance = gcnew OrderItem() ;
				*instance = *this ;
				return instance;
			}
			
			//= operator
			OrderItem% operator = ( OrderItem%  rhs)
			{
				title = rhs.title ;
				note = rhs.note ;
				quantity = rhs.quantity ;
				price = rhs.price ;
				return *this;
			}
			
			//DeepCopy
			void	DeepCopy ( OrderItem^  from)
			{
				title = from->title ;
				note = from->note ;
				quantity = from->quantity ;
				price = from->price ;
			}
			
		};
 
		[SerializableAttribute]
		public ref class	Address: public ICloneable
		{
		public:
			String^			name;
			int			zip;
			String^			city;
			String^			country;
			
			//default constructor
			Address()
			{
				name = String::Empty;
				zip = 0 ;
				city = String::Empty;
				country = String::Empty;
			}
			
			//copy constuctor
			Address( Address%  rhs){*this = rhs;}
			
			//IClonable Override
			virtual	Object^ Clone()
			{
				Address^	 instance = gcnew Address() ;
				*instance = *this ;
				return instance;
			}
			
			//= operator
			Address% operator = ( Address%  rhs)
			{
				name = rhs.name ;
				zip = rhs.zip ;
				city = rhs.city ;
				country = rhs.country ;
				return *this;
			}
			
			//DeepCopy
			void	DeepCopy ( Address^  from)
			{
				name = from->name ;
				zip = from->zip ;
				city = from->city ;
				country = from->country ;
			}
			
		};
	}
}


