//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
//Auto generated code
 
 
 
#pragma once
 
 
 
 
#include <string>
#include <vector>
#include <functional>
#include <algorithm>
using namespace std;
#include <tchar.h>
typedef basic_string<TCHAR> tstring;
 
 
 
 
 
 
namespace CustomerOrderAndFulfillment
{
	namespace CommonSchemaElements
	{
 
		class	CreditCardDetails
		{
		public:
			tstring			CCNumber;
			tstring			ExpirationDate;
			
			//default constructor
			CreditCardDetails()
			{
			}
			
			//Destructor
			~CreditCardDetails()
			{
			}
			
			//copy constuctor
			CreditCardDetails(const  CreditCardDetails& rhs){*this = rhs;}
			
			//= operator
			CreditCardDetails& operator = (const CreditCardDetails& rhs)
			{
				CCNumber = rhs.CCNumber ;
				ExpirationDate = rhs.ExpirationDate ;
				return *this;
			}
			
			};
 
			class	OrderItem
			{
			public:
				tstring				title;
				tstring				note;
				int				quantity;
				double				price;
			
				//default constructor
				OrderItem()
				{
					quantity = 0 ;
					price = 0.0 ;
				}
			
				//Destructor
				~OrderItem()
				{
				}
			
				//copy constuctor
				OrderItem(const  OrderItem& rhs){*this = rhs;}
			
				//= operator
				OrderItem& operator = (const OrderItem& rhs)
				{
					title = rhs.title ;
					note = rhs.note ;
					quantity = rhs.quantity ;
					price = rhs.price ;
					return *this;
				}
			
				};
 
				class	Address
				{
				public:
					tstring					name;
					int					zip;
					tstring					city;
					tstring					country;
			
					//default constructor
					Address()
					{
						zip = 0 ;
					}
			
					//Destructor
					~Address()
					{
					}
			
					//copy constuctor
					Address(const  Address& rhs){*this = rhs;}
			
					//= operator
					Address& operator = (const Address& rhs)
					{
						name = rhs.name ;
						zip = rhs.zip ;
						city = rhs.city ;
						country = rhs.country ;
						return *this;
					}
			
					};
				}
			}


