//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
 
package CustomerOrderAndFulfillment.Contract;
 
 
public	class	CustomerOrder implements Cloneable
{
	public	String	OrderNumber;
	public	CreditRating	Rating;
	public	CustomerOrderAndFulfillment.CommonSchemaElements.Address	AddressInfo;

	public	java.util.List<CustomerOrderAndFulfillment.CommonSchemaElements.OrderItem>	Orders;
	public	CustomerOrderAndFulfillment.CommonSchemaElements.CreditCardDetails	CcInfo;
			
	//default constructor
	public	CustomerOrder()
	{
		OrderNumber = "";
		Rating = CustomerOrderAndFulfillment.Contract.CreditRating.Good ;
		AddressInfo = new CustomerOrderAndFulfillment.CommonSchemaElements.Address() ;
		Orders = new java.util.ArrayList<CustomerOrderAndFulfillment.CommonSchemaElements.OrderItem>() ;
		CcInfo = new CustomerOrderAndFulfillment.CommonSchemaElements.CreditCardDetails() ;
	}
			
	//Clonable Override
	@Override  public	CustomerOrder clone()	throws CloneNotSupportedException
	{
		CustomerOrder	 instance = new CustomerOrder() ;
		instance.OrderNumber = OrderNumber ;
		instance.Rating = Rating ;
		instance.AddressInfo = (CustomerOrderAndFulfillment.CommonSchemaElements.Address)AddressInfo.clone() ;
		instance.Orders.addAll(Orders) ;
		instance.CcInfo = (CustomerOrderAndFulfillment.CommonSchemaElements.CreditCardDetails)CcInfo.clone() ;
		return instance;
	}
			
	//DeepCopy
	public	void DeepCopy(CustomerOrder rhs)
	{
		OrderNumber = rhs.OrderNumber ;
		Rating = rhs.Rating ;
		AddressInfo.DeepCopy(rhs.AddressInfo) ;
		Orders.addAll(rhs.Orders) ;
		CcInfo.DeepCopy(rhs.CcInfo) ;
	}
			
}


