//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
 
package CustomerOrderAndFulfillment.Contract;
 
 
public	class	FulfillmentRecord implements Cloneable
{
	public	String	FulfillmentRecordID;
	public	boolean	IsBackOrder;
	public	FuzzyCondition	StorageTemperature;
	public	String	CustomerOrderNo;
			
	//default constructor
	public	FulfillmentRecord()
	{
		FulfillmentRecordID = "";
		IsBackOrder = false ;
		StorageTemperature = CustomerOrderAndFulfillment.Contract.FuzzyCondition.Hot ;
		CustomerOrderNo = "";
	}
			
	//Clonable Override
	@Override  public	FulfillmentRecord clone()	throws CloneNotSupportedException
	{
		FulfillmentRecord	 instance = new FulfillmentRecord() ;
		instance.FulfillmentRecordID = FulfillmentRecordID ;
		instance.IsBackOrder = IsBackOrder ;
		instance.StorageTemperature = StorageTemperature ;
		instance.CustomerOrderNo = CustomerOrderNo ;
		return instance;
	}
			
	//DeepCopy
	public	void DeepCopy(FulfillmentRecord rhs)
	{
		FulfillmentRecordID = rhs.FulfillmentRecordID ;
		IsBackOrder = rhs.IsBackOrder ;
		StorageTemperature = rhs.StorageTemperature ;
		CustomerOrderNo = rhs.CustomerOrderNo ;
	}
			
}


