//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
 
package	CustomerOrderAndFulfillment.Contract;
 
//enumeration	FuzzyCondition
public enum	FuzzyCondition
{
	Hot("100"),
	VeryHot("200"),
	ExtremelyHot("300"),
	Cold("0")
			
	;
	private final String value;

	//private constructor
	FuzzyCondition(String value) 
	{	   this.value = value;}

	//fromValue
	public static FuzzyCondition fromValue(String value) 
	 {   
	   if (value != null) 
	   {   
	     for (FuzzyCondition v : values()) 
	     {   
	       if (v.value.equals(value)) 
	       {   
	         return v;   
	       }   
	     }   
	   }   
	   return null;   
	 } 

	//toString
	@Override
	public String toString() {   return value;}   
}
